### ISSUE TITLE
Github API rate exceeded

### ISSUE THREAD

**Issue by Nuruddinjr** [IonicaBizau/made-in#11]
After each call for a language, API rate exceeded

**Comment by hueitan** [comment]
Did you try the [GitHub Tokens](https://github.com/settings/tokens)?

**Comment by Nuruddinjr** [comment]
Yes, I created token, I added one token,and runned example, next time,I changed language to Python and I am getting error, rate exceeded

**Comment by hueitan** [comment]
There is nothing that the owner can do, you probably get a very big number of items, therefore rate exceeded. try to limit the location and language.

**Comment by IonicaBizau** [comment]
There are specific rate limits for the search API. Simply run your scripts with some delays. I remember I did some math to prevent this error (e.g. Fetching first N users, sorted by followers etc.).

**Comment by Nuruddinjr** [comment]
Thanks

**Comment by IonicaBizau** [comment]
To make it clearer, the search api rate limit is 30 requests / minute (*with* token). Therefore, I came up with fetching the first `29` users, sorted by followers (one request) and then another 29 requests for each user, to fetch repositories. This sums up to 30 requests. 😁 

Added a comment here: https://github.com/IonicaBizau/made-in/blob/master/lib/index.js#L40-L42
